# Generated by Django 5.2.5 on 2025-08-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ljubimac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('vrsta', models.CharField(max_length=50)),
                ('godine', models.IntegerField()),
            ],
        ),
    ]
