# Generated by Django 5.2.5 on 2025-08-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljubimci', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ljubimac',
            old_name='ime',
            new_name='ime_ljubimca',
        ),
        migrations.RemoveField(
            model_name='ljubimac',
            name='godine',
        ),
        migrations.RemoveField(
            model_name='ljubimac',
            name='vrsta',
        ),
        migrations.AddField(
            model_name='ljubimac',
            name='datum_rodenja_ljubimca',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ljubimac',
            name='vrsta_ljubimca',
            field=models.CharField(default='nepoznato', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Aktivnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_aktivnosti', models.CharField(max_length=100)),
                ('datum_aktivnosti', models.DateField()),
                ('trajanje_aktivnosti', models.IntegerField(help_text='Trajanje u minutama')),
                ('ljubimac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ljubimci.ljubimac')),
            ],
        ),
        migrations.CreateModel(
            name='Obrok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijeme_obroka', models.TimeField()),
                ('vrsta_hrane', models.CharField(max_length=100)),
                ('ljubimac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ljubimci.ljubimac')),
            ],
        ),
        migrations.CreateModel(
            name='Zdravlje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_pregleda', models.DateField()),
                ('tezina_ljubimca', models.FloatField()),
                ('sva_cjepiva_primljena', models.BooleanField(default=False)),
                ('bolesti', models.TextField(blank=True)),
                ('lijekovi', models.TextField(blank=True)),
                ('ljubimac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ljubimci.ljubimac')),
            ],
        ),
    ]
