# Generated by Django 5.2.5 on 2025-08-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljubimci', '0002_rename_ime_ljubimac_ime_ljubimca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZdravstveniZapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('tezina_ljubimca', models.FloatField(blank=True, null=True)),
                ('sva_cjepiva_primljena', models.BooleanField(default=False)),
                ('bolesti', models.TextField(blank=True)),
                ('lijekovi', models.TextField(blank=True)),
                ('opis', models.TextField(blank=True)),
                ('ljubimac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapisi', to='ljubimci.ljubimac')),
            ],
        ),
        migrations.DeleteModel(
            name='Zdravlje',
        ),
    ]
